### PR TITLE
Expand acceptable bounds to [-360,-95,360,95]. Fixes #113

### LINKED ISSUE #113: Expand acceptable bounds beyond 180 and 90
The bounds checking in tilelive.js is too far on the cautious side and ends up marking common data sources as invalid, as well as datasources that include outside longitude values in order to represent dateline wrapping. These should be expanded to +/-360 and +/-95

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by rclark** [comment]
The only difficulty that I'm seeing here is that the read streams rely on taking the dataset bounds and running them through `sphericalmercator.xyz(bounds, zoom)` to find [the range of tiles that will be pulled from the source](https://github.com/mapbox/tilelive.js/blob/8e75e6e6f666b63dd4bc987b67fab56dcc43b1f5/lib/stream-scanline.js#L43-L57).

We start getting strange behavior if we hand in wrapping bounds:

```
> var bounds = [-290,-10,-170,10];
> sm.xyz(bounds, 5);
{ minX: -10,
  minY: 15,
  maxX: 0,
  maxY: 16 }
> var bounds = [175,-10,275,10];
> sm.xyz(bounds, 5);
{ minX: 31,
  minY: 15,
  maxX: 31,
  maxY: 16 }
```

This could as simple as an adjustment of the rendering bounds in the `stream-scanline` and `stream-pyramid` cases, I believe.

**Comment by yhahn** [comment]
@rclark @tmcw right, so fix is to just clip overflowing bounds to `[-180,-90,180,90]` respectively in these streams?

**Comment by tmcw** [comment]
:+1: added a method that limits the bounds that those streams iterate over

**Comment by yhahn** [comment]
Looks great -- @rclark third pair of eyes before merge?

**Comment by rclark** [comment]
:+1: Let's just make sure that we make it as clear as possible that *we're still going to clip your data at the dateline*, but that at least we won't throw the whole thing out.

**Pull request merged**
